### PR TITLE
feat(custom-icon): add option to change icon

### PR DESCRIPTION
**Pull request by rifqempul**
issue : #11 #2 

Hello this is my first PR for Open Source Project.
Also my first experience with qml or any KDE software.

I made some adjustment to add custom icon. 

i expect your review if it's possible. I will correct any mistakes.

### CODE REVIEW

**Comment by truly-irham** [comment]
Hi there, thanks for this pr. It works great on my kde (arch btw). I hope op can merge this for everyone's ease of use.

**Comment by FunMLG** [comment]
Ohhhh my god thank you so much !!!!
It works perfectly
Hope this will be merged

**Comment by FunMLG** [comment]
In fact, the project is under the GNU GPL license so you can redistribute your modified code... 😏

**Comment by marcelovicentegc** [comment]
Hi, @rborgniet. Mind taking a look at this?

**Comment by rborgniet** [comment]
Hello to all! Really sorry for the long delay... I just analyzed your code @rifqempul it works great and perfectly! Thanks again for all the support about this project.

**Pull request merged**
